apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs
  namespace: {{ .Values.namespace }}
  labels:
    app: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - name: shell
          image: {{ .Values.imageRegistry }}/{{ .Values.imagePath }}:{{ .Values.imageTag }}
          # ports:
          #   - containerPort: 80
          #   - containerPort: 30100
          # resources: {}
          # command: [ "/bin/bash", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 30