apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/"
    server: nfs-server