apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argocd
  name: nfs-pv-claim
spec:
  # storageClassName: nfs-direct
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi