apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argocd
  name: nfs-pvc
spec:
  storageClassName: nfs-direct
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi