apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: {{ .Values.namespace }}
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alpine
    spec:
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pv-claim
      containers:
        - name: shell
          image: {{ .Values.imageRegistry }}/{{ .Values.imagePath }}:{{ .Values.imageTag }}
          volumeMounts:
            - name: nfs-volume
              mountPath: /nfs-client-share
          ports:
            - containerPort: 80
            - containerPort: 30100
          resources: {}
          securityContext:
            privileged: true 
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 30

      # volumes:
      #   - name: nfs-pvc
      #     persistentVolumeClaim:
      #       claimName: test-dynamic-volume-claim