apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  type: NodePort


apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  replicas: 1
  strategy:
    type: Recreate
    spec:
      containers:
        - image: github.com/robschaap242/hermes.git
          name: alpine
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
