apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: {{ .Values.namespace }}
  labels:
    app: alpine
spec:
  replicas: 1
  strategy:
    type: Recreate
    selector:
      matchLabels:
        app: alpine
    containers:
      - image: github.com/robschaap242/hermes.git
        name: alpine
    restartPolicy: Always
    terminationGracePeriodSeconds: 30
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: shell
          image: {{ .Values.imageRegistry }}/{{ .Values.imagePath }}:{{ .Values.imageTag }}
          # ports:
          #   - containerPort: 80
          #   - containerPort: 30100
          # resources: {}
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30