apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bt-nfs-client
  namespace: brasstax
  name: bt-nfs-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bt-nfs-client
  template:
    metadata:
      labels:
        app: bt-nfs-client
    spec:
      volumes:
        - name: bt-nfs-volume
          nfs:
            server: bt-nfs-box
            path: /
      containers:
      - name: bt-nfs-client
        image: robschaap242/hermes-nfs-client:0.0.5
        env:
        - name: SERVER
          value: 10.103.32.174
        - name: SHARE
          value: /nfs-share
        ports:
        - name: "nfs-port"  
          containerPort: 2049
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: bt-nfs-client-service
  namespace: brasstax
spec:
  type: NodePort
  selector:
    app: bt-nfs-client
  ports:
    - name: "nfs-port"
      port: 80
      protocol: TCP
    - name: "default-port"
      port: 2049
      protocol: TCP