version: "2.1"
services:
  nfs-client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nfs-client
    restart: unless-stopped
    privileged: true
    environment:
      - SHARE=/data
      - SERVER=nfs-server.ola-zeus:2049
    command: ["tail", "-f", "/dev/null"]
